### ISSUE TITLE
Getting error on install

### ISSUE THREAD

**Issue by queso** [xdissent/meteor-cucumber#1]
After I did an `mrt add cucumber` I got this error:

```
cucumber: updating npm dependencies -- cucumber, chokidar, zombie, disrequire...
=> Errors while scanning packages:

While building package `cucumber`:
error: no such package: 'selenium'
error: no such package: 'mirror'
```

**Comment by xdissent** [comment]
My bad, I forgot to put those deps in `smart.json`. If you `mrt add selenium` and `mrt add mirror` within your app it should work for now.

**Comment by queso** [comment]
Yeah, just figured that add.  Thx.
