### ISSUE TITLE
Error when trying to add Collection data in a step.

### ISSUE THREAD

**Issue by queso** [xdissent/meteor-cucumber#2]
I20140513-14:46:36.289(-4)? @zombie
I20140513-14:46:36.290(-4)? Feature: See all posted episodes
I20140513-14:46:36.290(-4)?   As a visitor to the site
I20140513-14:46:36.290(-4)?   I want to see all published episodes
I20140513-14:46:36.290(-4)?   So that I can browser and listen to a podcast
I20140513-14:46:36.290(-4)?
I20140513-14:46:37.138(-4)?
I20140513-14:46:37.138(-4)?   Scenario: Go to the home page to see all episodes   # Users/josh/Code/Differential/microphone/tests/features/episodes.feature:7
I20140513-14:46:37.144(-4)?     Given 3 episodes exist                            # Users/josh/Code/Differential/microphone/tests/features/episodes.feature:8
I20140513-14:46:37.145(-4)?       Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
I20140513-14:46:37.145(-4)?         at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor.js:870:11)
I20140513-14:46:37.145(-4)?         at Object.Meteor.bindEnvironment (packages/meteor.js:927:10)
I20140513-14:46:37.145(-4)?         at [object Object].<anonymous> (packages/meteor.js:181:27)
I20140513-14:46:37.145(-4)?         at [object Object].MongoConnection.(anonymous function) [as insert](packages/mongo-livedata.js:591:50)
I20140513-14:46:37.146(-4)?         at Object.CollectionHooks.defineAdvice.self (packages/collection-hooks.js:230:18)
I20140513-14:46:37.146(-4)?         at Object.(anonymous function) [as insert](packages/collection-hooks.js:87:21)
I20140513-14:46:37.146(-4)?         at [object Object].Meteor.Collection.(anonymous function) [as insert](packages/mongo-livedata.js:3383:47)
I20140513-14:46:37.146(-4)?         at Episode.Minimongoid.Minimongoid.save (packages/minimongoid.js:264:57)
I20140513-14:46:37.146(-4)?         at Function.Minimongoid.Minimongoid.create (packages/minimongoid.js:352:15)
I20140513-14:46:37.146(-4)?         at MultiWorld.<anonymous> (/Users/josh/Code/Differential/microphone/tests/features/step_definitions/episodes.js:4:20)

**Comment by xdissent** [comment]
Yeah, sorry I'm still working on auto-binding the Meteor environment in support code so it runs within a Fiber. In the meantime, you can use `Meteor.bindEnvironment` directly on your callbacks like this:

``` coffee
module.exports = ->

  @Given /^I am a website visitor using zombie$/, Meteor.bindEnvironment (callback) ->
    TestCollection.insert name: 'testing'
    callback()
```

**Comment by queso** [comment]
That seems to have gotten me working, thx!

Also, it looks like the data is inserted into my running dev environment...  Is there a way to have it clean itself up, or no?

**Comment by xdissent** [comment]
Hmm, it shouldn't be touching your dev db. The tests run in another app instance pointed at `mongodb://127.0.0.1:3001/cucumber`. I'll take a look in a bit to make sure that's still the case. Anyway, you can clean anything up with "after" hooks.

**Comment by xdissent** [comment]
I just pushed a fix that (rather painfully) wraps all step definitions and hooks in the appropriate meteor environment and does the same for zombie helper callbacks. You should be able to remove the Meteor.bindEnvironment now and expect the callbacks you pass to zombie's methods to run within a fiber as well. I also checked my db and all modifications seem to be within the 'cucumber' db only. Let me know if that's not the case for you. Note that if you don't have the mirror package installed (and used in your packages file) then the tests will run within the context of your real app, and the actual db will be modified.

**Comment by queso** [comment]
Looks like it is fixed now.
